services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    start: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
